// GENERATED from engine/src/generate-files.ts — DO NOT EDIT.
// Source of truth: engine/src. Regenerate: node engine/scripts/sync-to-web.mjs

// Render the agent-context files (CLAUDE.md / AGENTS.md / llms.txt) from the context
// store. These are what a fresh AI session loads to "start warm" — the Context Handoff.

import type { ContextItem } from "./types";

function byType(items: ContextItem[]) {
  const active = items.filter((i) => i.status === "active");
  return {
    decisions: active.filter((i) => i.type === "decision" || i.type === "adr"),
    conventions: active.filter((i) => i.type === "convention"),
    glossary: active.filter((i) => i.type === "glossary"),
    notes: active.filter((i) => i.type === "note"),
  };
}

export function renderClaudeMd(project: string, items: ContextItem[]): string {
  const g = byType(items);
  const lines: string[] = [
    `# CLAUDE.md — ${project}`,
    "",
    "> Team context loaded by ContextOS. This file makes a fresh AI session start *warm* —",
    "> it inherits the team's decisions, conventions, and glossary so it stops repeating known mistakes.",
    "",
  ];
  if (g.conventions.length) {
    lines.push("## Conventions (follow these)");
    for (const c of g.conventions) lines.push(`- **${c.title}** — ${c.body}`);
    lines.push("");
  }
  if (g.decisions.length) {
    lines.push("## Decisions (respect these; do not re-litigate)");
    for (const d of g.decisions) lines.push(`- **${d.title}** — ${d.body}`);
    lines.push("");
  }
  if (g.glossary.length) {
    lines.push("## Glossary");
    for (const t of g.glossary) lines.push(`- **${t.title}**: ${t.body}`);
    lines.push("");
  }
  if (g.notes.length) {
    lines.push("## Notes");
    for (const n of g.notes) lines.push(`- ${n.title}: ${n.body}`);
    lines.push("");
  }
  lines.push(`_Generated by ContextOS · ${new Date().toISOString().slice(0, 10)}_`);
  return lines.join("\n");
}

export function renderAgentsMd(project: string, items: ContextItem[]): string {
  const g = byType(items);
  const lines: string[] = [
    `# AGENTS.md — ${project}`,
    "",
    "Standard agent-instructions file, generated from ContextOS team context. Any agent",
    "(Cursor, Windsurf, Claude Code, OpenAI/Codex, Gemini) should follow these.",
    "",
    "## Rules of engagement",
  ];
  for (const c of g.conventions) lines.push(`- ${c.body}`);
  for (const d of g.decisions) lines.push(`- Respect: ${d.title} — ${d.body}`);
  lines.push("");
  if (g.glossary.length) {
    lines.push("## Domain terms");
    for (const t of g.glossary) lines.push(`- ${t.title}: ${t.body}`);
    lines.push("");
  }
  lines.push("_Generated by ContextOS. Edit context in ContextOS, not here._");
  return lines.join("\n");
}

export function renderLlmsTxt(project: string, items: ContextItem[]): string {
  const g = byType(items);
  const lines: string[] = [
    `# ${project} — team context`,
    "",
    "> Institutional context for AI tools, exported by ContextOS (open Context Handoff format).",
    "",
    `## Conventions (${g.conventions.length})`,
    ...g.conventions.map((c) => `- ${c.title}`),
    "",
    `## Decisions (${g.decisions.length})`,
    ...g.decisions.map((d) => `- ${d.title}`),
    "",
    `## Glossary (${g.glossary.length})`,
    ...g.glossary.map((t) => `- ${t.title}`),
  ];
  return lines.join("\n");
}

export function renderAll(project: string, items: ContextItem[]): Record<string, string> {
  return {
    "CLAUDE.md": renderClaudeMd(project, items),
    "AGENTS.md": renderAgentsMd(project, items),
    "llms.txt": renderLlmsTxt(project, items),
  };
}
